### PR TITLE
Settings

### LINKED ISSUE #13: Settings toggle/dropdown

### PR DESCRIPTION
**Pull request by josh-velasquez**
Implemented dropdown for settings

### CODE REVIEW

**Review by emilio-alvarez — COMMENTED** [review]
Theres a tiny gap between the settings button, and the drop down. If you don't move your mouse to the dropdown super quickly, it closes, which is kinda frustrating. Is there a way to either remove the gap or add a little delay?

**Comment by josh-velasquez** [comment]
> Theres a tiny gap between the settings button, and the drop down. If you don't move your mouse to the dropdown super quickly, it closes, which is kinda frustrating. Is there a way to either remove the gap or add a little delay?

I

**Comment by josh-velasquez** [comment]
> Theres a tiny gap between the settings button, and the drop down. If you don't move your mouse to the dropdown super quickly, it closes, which is kinda frustrating. Is there a way to either remove the gap or add a little delay?

**Comment by josh-velasquez** [comment]
> Theres a tiny gap between the settings button, and the drop down. If you don't move your mouse to the dropdown super quickly, it closes, which is kinda frustrating. Is there a way to either remove the gap or add a little delay?

On the Semantic UI website, the dropdown didn't have any gaps in it which is weird that ours does. I tried adjusting the bottom margin and it didn't work (the gap is gone but its "invisibly" there still). Once we have the whole header fixed I'll see if I can do something about it.

**Review by emilio-alvarez — COMMENTED** [review]
What if instead of hovering we just make them click to open the dropdown? Seems like what most places do, and I feel like I remember my boss at internship saying how he had to figure out a similar issue with their dropdowns, and how it was a struggle.

I instinctively wanted to click the button.

Edit: Seems like for it to be clickable, semantic-ui needs to use javascript. And for some reason that doesn't work. Or am I imagining things?

**Review by jeffh1996 — APPROVED** [review]

**Pull request merged**
